/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.ConexionMetodos;

/**
 *
 * @author Danie
 */
public class Diagnostico extends javax.swing.JFrame {

    /**
     * Creates new form GrupoOcup
     */
    public Diagnostico() {
        initComponents();
         CargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnl_Contenedor = new javax.swing.JPanel();
        jPnl_BarraTittle = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPnl_ContenedorTabla = new javax.swing.JPanel();
        jSp_ContenedorTabla = new javax.swing.JScrollPane();
        jTbl_Datos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnl_Contenedor.setBackground(new java.awt.Color(113, 127, 131));
        jPnl_Contenedor.setLayout(null);

        jPnl_BarraTittle.setBackground(new java.awt.Color(44, 62, 80));
        jPnl_BarraTittle.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(245, 245, 245));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Diagnostico");
        jPnl_BarraTittle.add(jLabel5);
        jLabel5.setBounds(320, 0, 230, 30);

        jPnl_Contenedor.add(jPnl_BarraTittle);
        jPnl_BarraTittle.setBounds(0, -1, 850, 30);

        jPnl_ContenedorTabla.setBackground(new java.awt.Color(44, 62, 80));
        jPnl_ContenedorTabla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPnl_ContenedorTabla.setOpaque(false);
        jPnl_ContenedorTabla.setLayout(null);

        jTbl_Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jSp_ContenedorTabla.setViewportView(jTbl_Datos);

        jPnl_ContenedorTabla.add(jSp_ContenedorTabla);
        jSp_ContenedorTabla.setBounds(10, 10, 790, 290);

        jPnl_Contenedor.add(jPnl_ContenedorTabla);
        jPnl_ContenedorTabla.setBounds(10, 40, 820, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl_Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl_Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarTabla()
    {
        //abro la conexion
        ConexionMetodos JM = new ConexionMetodos();
        //hago la consulta que cargara la tabla
        String consulta = "select * from [diagnostico]";
        
        //seteo el modelo a la tabla
        jTbl_Datos.setModel(JM.LlenarJTable(consulta));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diagnostico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPnl_BarraTittle;
    private javax.swing.JPanel jPnl_Contenedor;
    private javax.swing.JPanel jPnl_ContenedorTabla;
    private javax.swing.JScrollPane jSp_ContenedorTabla;
    private javax.swing.JTable jTbl_Datos;
    // End of variables declaration//GEN-END:variables
}
