/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.ConexionMetodos;

/**
 *
 * @author Danie
 */
public class Empleados extends javax.swing.JFrame {

    /**
     * Creates new form Empleados
     */
    public Empleados() {
        initComponents();
        LlenarCargosDepartemento();
         LlenarCargosPuesto();
         LlenarCargosEstablecimiento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnl_Contenedor = new javax.swing.JPanel();
        jPnl_BarraTittle = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPnl_ContenedorTabla = new javax.swing.JPanel();
        jSp_ContenedorTabla = new javax.swing.JScrollPane();
        jTbl_Datos = new javax.swing.JTable();
        jPnl_Controles = new javax.swing.JPanel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt10 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt11 = new javax.swing.JTextField();
        cmb2 = new javax.swing.JComboBox<>();
        cmb3 = new javax.swing.JComboBox<>();
        cmb1 = new javax.swing.JComboBox<>();
        jPnl_Botones = new javax.swing.JPanel();
        jBtn_Agregar = new javax.swing.JButton();
        jBtn_Modificar = new javax.swing.JButton();
        jBtn_Consultar = new javax.swing.JButton();
        jBtn_Eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnl_Contenedor.setBackground(new java.awt.Color(113, 127, 131));
        jPnl_Contenedor.setLayout(null);

        jPnl_BarraTittle.setBackground(new java.awt.Color(44, 62, 80));
        jPnl_BarraTittle.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(245, 245, 245));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Empleados");
        jPnl_BarraTittle.add(jLabel5);
        jLabel5.setBounds(320, 0, 230, 30);

        jPnl_Contenedor.add(jPnl_BarraTittle);
        jPnl_BarraTittle.setBounds(0, -1, 850, 30);

        jPnl_ContenedorTabla.setBackground(new java.awt.Color(44, 62, 80));
        jPnl_ContenedorTabla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPnl_ContenedorTabla.setOpaque(false);
        jPnl_ContenedorTabla.setLayout(null);

        jTbl_Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTbl_Datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTbl_DatosMousePressed(evt);
            }
        });
        jSp_ContenedorTabla.setViewportView(jTbl_Datos);

        jPnl_ContenedorTabla.add(jSp_ContenedorTabla);
        jSp_ContenedorTabla.setBounds(10, 10, 790, 150);

        jPnl_Contenedor.add(jPnl_ContenedorTabla);
        jPnl_ContenedorTabla.setBounds(10, 450, 820, 170);

        jPnl_Controles.setBackground(new java.awt.Color(44, 62, 80));
        jPnl_Controles.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPnl_Controles.setOpaque(false);
        jPnl_Controles.setLayout(null);

        txtCodigo.setEditable(false);
        jPnl_Controles.add(txtCodigo);
        txtCodigo.setBounds(100, 5, 290, 20);

        jLabel2.setForeground(new java.awt.Color(245, 245, 245));
        jLabel2.setText("Codigo");
        jPnl_Controles.add(jLabel2);
        jLabel2.setBounds(10, 5, 90, 14);

        jLabel3.setForeground(new java.awt.Color(245, 245, 245));
        jLabel3.setText("Salario:");
        jPnl_Controles.add(jLabel3);
        jLabel3.setBounds(10, 360, 160, 14);

        jLabel4.setForeground(new java.awt.Color(245, 245, 245));
        jLabel4.setText("Nombre:");
        jPnl_Controles.add(jLabel4);
        jLabel4.setBounds(10, 40, 160, 14);

        jLabel6.setForeground(new java.awt.Color(245, 245, 245));
        jLabel6.setText("Sexo:");
        jPnl_Controles.add(jLabel6);
        jLabel6.setBounds(10, 60, 160, 14);

        jLabel7.setForeground(new java.awt.Color(245, 245, 245));
        jLabel7.setText("Estado civil:");
        jPnl_Controles.add(jLabel7);
        jLabel7.setBounds(10, 90, 160, 14);

        jLabel8.setForeground(new java.awt.Color(245, 245, 245));
        jLabel8.setText("Fecha ingreso:");
        jPnl_Controles.add(jLabel8);
        jLabel8.setBounds(10, 110, 160, 14);

        jLabel9.setForeground(new java.awt.Color(245, 245, 245));
        jLabel9.setText("Fecha salida:");
        jPnl_Controles.add(jLabel9);
        jLabel9.setBounds(10, 140, 160, 14);

        jLabel10.setForeground(new java.awt.Color(245, 245, 245));
        jLabel10.setText("Departemento:");
        jPnl_Controles.add(jLabel10);
        jLabel10.setBounds(10, 160, 160, 14);

        jLabel11.setForeground(new java.awt.Color(245, 245, 245));
        jLabel11.setText("Puesto:");
        jPnl_Controles.add(jLabel11);
        jLabel11.setBounds(10, 190, 160, 14);

        jLabel12.setForeground(new java.awt.Color(245, 245, 245));
        jLabel12.setText("Fecha nacimiento:");
        jPnl_Controles.add(jLabel12);
        jLabel12.setBounds(10, 210, 160, 14);

        jLabel13.setForeground(new java.awt.Color(245, 245, 245));
        jLabel13.setText("Direccion:");
        jPnl_Controles.add(jLabel13);
        jLabel13.setBounds(10, 240, 160, 14);

        jLabel14.setForeground(new java.awt.Color(245, 245, 245));
        jLabel14.setText("Telefono 1:");
        jPnl_Controles.add(jLabel14);
        jLabel14.setBounds(10, 260, 160, 14);

        jLabel15.setForeground(new java.awt.Color(245, 245, 245));
        jLabel15.setText("Telefono 2:");
        jPnl_Controles.add(jLabel15);
        jLabel15.setBounds(10, 290, 160, 14);

        jLabel16.setForeground(new java.awt.Color(245, 245, 245));
        jLabel16.setText("Notas");
        jPnl_Controles.add(jLabel16);
        jLabel16.setBounds(10, 310, 160, 14);

        jLabel17.setForeground(new java.awt.Color(245, 245, 245));
        jLabel17.setText("Establecimiento:");
        jPnl_Controles.add(jLabel17);
        jLabel17.setBounds(10, 340, 160, 14);
        jPnl_Controles.add(txt10);
        txt10.setBounds(100, 310, 290, 20);
        jPnl_Controles.add(txt1);
        txt1.setBounds(100, 35, 290, 20);
        jPnl_Controles.add(txt4);
        txt4.setBounds(100, 110, 290, 20);
        jPnl_Controles.add(txt5);
        txt5.setBounds(100, 135, 290, 20);
        jPnl_Controles.add(txt6);
        txt6.setBounds(100, 210, 290, 20);
        jPnl_Controles.add(txt7);
        txt7.setBounds(100, 235, 290, 20);
        jPnl_Controles.add(txt8);
        txt8.setBounds(100, 260, 290, 20);
        jPnl_Controles.add(txt9);
        txt9.setBounds(100, 285, 290, 20);
        jPnl_Controles.add(txt3);
        txt3.setBounds(100, 85, 290, 20);
        jPnl_Controles.add(txt2);
        txt2.setBounds(100, 60, 290, 20);
        jPnl_Controles.add(txt11);
        txt11.setBounds(100, 360, 290, 20);

        cmb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPnl_Controles.add(cmb2);
        cmb2.setBounds(100, 185, 290, 20);

        cmb3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPnl_Controles.add(cmb3);
        cmb3.setBounds(100, 335, 290, 20);

        cmb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPnl_Controles.add(cmb1);
        cmb1.setBounds(100, 160, 290, 20);

        jPnl_Contenedor.add(jPnl_Controles);
        jPnl_Controles.setBounds(10, 30, 580, 410);

        jPnl_Botones.setBackground(new java.awt.Color(44, 62, 80));
        jPnl_Botones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPnl_Botones.setOpaque(false);
        jPnl_Botones.setLayout(null);

        jBtn_Agregar.setText("Agregar");
        jBtn_Agregar.setToolTipText("");
        jBtn_Agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_Agregar.setIconTextGap(0);
        jBtn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_AgregarActionPerformed(evt);
            }
        });
        jPnl_Botones.add(jBtn_Agregar);
        jBtn_Agregar.setBounds(20, 10, 200, 30);

        jBtn_Modificar.setText("Modificar");
        jBtn_Modificar.setToolTipText("");
        jBtn_Modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_Modificar.setIconTextGap(0);
        jBtn_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ModificarActionPerformed(evt);
            }
        });
        jPnl_Botones.add(jBtn_Modificar);
        jBtn_Modificar.setBounds(20, 50, 200, 30);

        jBtn_Consultar.setText("Consultar");
        jBtn_Consultar.setToolTipText("");
        jBtn_Consultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_Consultar.setIconTextGap(0);
        jBtn_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ConsultarActionPerformed(evt);
            }
        });
        jPnl_Botones.add(jBtn_Consultar);
        jBtn_Consultar.setBounds(20, 130, 200, 30);

        jBtn_Eliminar.setText("Eliminar");
        jBtn_Eliminar.setToolTipText("");
        jBtn_Eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtn_Eliminar.setIconTextGap(0);
        jBtn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_EliminarActionPerformed(evt);
            }
        });
        jPnl_Botones.add(jBtn_Eliminar);
        jBtn_Eliminar.setBounds(20, 90, 200, 30);

        jPnl_Contenedor.add(jPnl_Botones);
        jPnl_Botones.setBounds(596, 36, 230, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl_Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnl_Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ConsultarActionPerformed
        // TODO add your handling code here:
        CargarTabla();
    }//GEN-LAST:event_jBtn_ConsultarActionPerformed

    private void jTbl_DatosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbl_DatosMousePressed
        // TODO add your handling code here:
            String consulta = "select e.id_empleado ,e.nombre,e.sexo,e.estado_civil,e.fecha_ingreso,e.fecha_salida ,es.descripcion,p.descripcion,e.fecha_nacimiento,e.direccion,e.telefono1,e.telefono2,e.notas,es.descripcion,e.salario from empleados e,departamento D,establecimiento es,puesto p\n" +
" WHERE E.e_departamento =D.id_departamento AND e.establecimiento =es.id_establecimiento AND e.puesto =p.id_puesto AND e.estado =1 ";
        
        int fila_seleccionada = jTbl_Datos.getSelectedRow();
         txtCodigo.setText(jTbl_Datos.getValueAt(fila_seleccionada, 0).toString());
         txt1.setText(jTbl_Datos.getValueAt(fila_seleccionada,1).toString());
         txt2.setText(jTbl_Datos.getValueAt(fila_seleccionada,2).toString());
         txt3.setText(jTbl_Datos.getValueAt(fila_seleccionada,3).toString());
         txt4.setText(jTbl_Datos.getValueAt(fila_seleccionada,4).toString());
         txt5.setText(jTbl_Datos.getValueAt(fila_seleccionada,5).toString());
          cmb1.setSelectedItem(jTbl_Datos.getValueAt(fila_seleccionada, 6).toString());
         cmb2.setSelectedItem(jTbl_Datos.getValueAt(fila_seleccionada, 7).toString());
         txt6.setText(jTbl_Datos.getValueAt(fila_seleccionada,8).toString());
         txt7.setText(jTbl_Datos.getValueAt(fila_seleccionada,9).toString());
         txt8.setText(jTbl_Datos.getValueAt(fila_seleccionada,10).toString());
         txt9.setText(jTbl_Datos.getValueAt(fila_seleccionada,11).toString());
         txt10.setText(jTbl_Datos.getValueAt(fila_seleccionada,12).toString());
         cmb3.setSelectedItem(jTbl_Datos.getValueAt(fila_seleccionada, 13).toString());
         txt11.setText(jTbl_Datos.getValueAt(fila_seleccionada,14).toString());
         
        
    }//GEN-LAST:event_jTbl_DatosMousePressed

    private void jBtn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_AgregarActionPerformed
        // TODO add your handling code here:
          String txtt1 = txt1.getText();
          String txtt2 = txt2.getText();
          String txtt3 = txt3.getText();
           String txtt4 = txt4.getText();
           String txtt5 = txt5.getText();
           String txtt6 = txt6.getText();
           String txtt7 = txt7.getText();
           String txtt8 = txt8.getText();
           String txtt9 = txt9.getText();
           String txtt10 = txt10.getText();
           String txtt11 = txt11.getText();

            String cmbb1 = cmb1.getSelectedItem().toString();
            String cmbb2 = cmb2.getSelectedItem().toString();
            String cmbb3 = cmb3.getSelectedItem().toString();
         ConexionMetodos cm1 = new ConexionMetodos();
          String consulta = "select id_departamento from departamento where descripcion ='"+cmbb1+"'";
         String cmb11 = cm1.ObtenerValor("id_departamento", consulta);
         
          ConexionMetodos cm2 = new ConexionMetodos();
          String consulta2 = "select id_puesto from puesto where descripcion ='"+cmbb2+"'";
         String cmb12 = cm2.ObtenerValor("id_puesto", consulta2);
         
          ConexionMetodos cm3 = new ConexionMetodos();      
          String consulta3 = "select id_establecimiento from establecimiento where descripcion ='"+cmbb3+"'";
         String cmb13 = cm3.ObtenerValor("id_establecimiento", consulta3);
         
         
         
          ConexionMetodos JM = new ConexionMetodos();
        //hago la consulta que cargara la tabla
         consulta = "insert into [empleados] values ('"+txtt1+"','"+txtt2+"','"+txtt3+"','"+txtt4+"','"+txtt5+"',"+cmb11+","+cmb12+",'"+txtt6+"','"+txtt7+"','"+txtt8+"','"+txtt9+"','"+txtt10+"',"+cmb13+",'"+txtt11+"',1)";
        System.out.println(consulta);
        JM.EjecutarConsulta(consulta);
        
    }//GEN-LAST:event_jBtn_AgregarActionPerformed

    private void jBtn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_EliminarActionPerformed
        // TODO add your handling code here:
         String id = txtCodigo.getText();
         ConexionMetodos OBT = new ConexionMetodos();
         
         // String consulta = "delete diagnostico where id_diagnostico= "+id+"";
           String consulta = "update [empleados] set [estado]=2 where id_empleado="+id+" and estado = 1 ";
      OBT.EjecutarConsulta( consulta);
    }//GEN-LAST:event_jBtn_EliminarActionPerformed

    private void jBtn_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ModificarActionPerformed
        // TODO add your handling code here:
         String txtcodigo = txtCodigo.getText();
         String txtt1 = txt1.getText();
          String txtt2 = txt2.getText();
          String txtt3 = txt3.getText();
           String txtt4 = txt4.getText();
           String txtt5 = txt5.getText();
           String txtt6 = txt6.getText();
           String txtt7 = txt7.getText();
           String txtt8 = txt8.getText();
           String txtt9 = txt9.getText();
           String txtt10 = txt10.getText();
           String txtt11 = txt11.getText();

            String cmbb1 = cmb1.getSelectedItem().toString();
            String cmbb2 = cmb2.getSelectedItem().toString();
            String cmbb3 = cmb3.getSelectedItem().toString();
         ConexionMetodos cm1 = new ConexionMetodos();
          String consulta = "select id_departamento from departamento where descripcion ='"+cmbb1+"'";
         String cmb11 = cm1.ObtenerValor("id_departamento", consulta);
         
          ConexionMetodos cm2 = new ConexionMetodos();
          String consulta2 = "select id_puesto from puesto where descripcion ='"+cmbb2+"'";
         String cmb12 = cm2.ObtenerValor("id_puesto", consulta2);
         
          ConexionMetodos cm3 = new ConexionMetodos();      
          String consulta3 = "select id_establecimiento from establecimiento where descripcion ='"+cmbb3+"'";
         String cmb13 = cm3.ObtenerValor("id_establecimiento", consulta3);
         
         
         
          ConexionMetodos JM = new ConexionMetodos();
        //hago la consulta que cargara la tabla
         consulta = "insert into [empleados] values ('"+txtt1+"','"+txtt2+"','"+txtt3+"','"+txtt4+"','"+txtt5+"',"+cmb11+","+cmb12+",'"+txtt6+"','"+txtt7+"','"+txtt8+"','"+txtt9+"','"+txtt10+"',"+cmb13+",'"+txtt11+"',1)";
         consulta = "UPDATE [dbo].[empleados]   SET [nombre] = '"+txtt1+"' " +
"      ,[sexo] = '"+txtt2+"' " +
"      ,[estado_civil] = '"+txtt3+"'" +
"      ,[fecha_ingreso] = '"+txtt4+"'" +
"      ,[fecha_salida] ='"+txtt5+"'" +
"      ,[e_departamento] = "+cmb11+"" +
"      ,[puesto] = "+cmb12+"" +
"      ,[fecha_nacimiento] = '"+txtt6+"'" +
"      ,[direccion] = '"+txtt7+"'" +
"      ,[telefono1] = '"+txtt8+"'" +
"      ,[telefono2] = '"+txtt9+"'" +
"      ,[notas] = '"+txtt10+"'" +
"      ,[establecimiento] = "+cmb13+"" +
"      ,[salario] = '"+txtt11+"' WHERE  id_empleado = "+txtcodigo+"";
        
         System.out.println(consulta);
        JM.EjecutarConsulta(consulta);
        
    }//GEN-LAST:event_jBtn_ModificarActionPerformed
    
     private void LlenarCargosDepartemento()
    {
        ConexionMetodos CM = new ConexionMetodos();
        String carga_cmb = "descripcion";
       // String consulta = "select E.nombre from empleados E, incapacidad I WHERE I.i_grupoocup =E.id_empleado";
       String consulta = "select d.descripcion from departamento d";
        cmb1.setModel(CM.LlenarCombobox(carga_cmb, consulta));
    }
      private void LlenarCargosPuesto()
    {
        ConexionMetodos CM = new ConexionMetodos();
        String carga_cmb = "descripcion";
       // String consulta = "select E.nombre from empleados E, incapacidad I WHERE I.i_grupoocup =E.id_empleado";
       String consulta = "select p.descripcion from puesto p";
        cmb2.setModel(CM.LlenarCombobox(carga_cmb, consulta));
    }
  private void LlenarCargosEstablecimiento()
    {
        ConexionMetodos CM = new ConexionMetodos();
        String carga_cmb = "descripcion";
       // String consulta = "select E.nombre from empleados E, incapacidad I WHERE I.i_grupoocup =E.id_empleado";
       String consulta = "select e.descripcion from establecimiento e";
        cmb3.setModel(CM.LlenarCombobox(carga_cmb, consulta));
    }    
    private void CargarTabla()
    {
        //abro la conexion
        ConexionMetodos JM = new ConexionMetodos();
        //hago la consulta que cargara la tabla
        String consulta = "select e.id_empleado ,e.nombre,e.sexo,e.estado_civil,e.fecha_ingreso,e.fecha_salida ,es.descripcion,p.descripcion,e.fecha_nacimiento,e.direccion,e.telefono1,e.telefono2,e.notas,es.descripcion,e.salario from empleados e,departamento D,establecimiento es,puesto p\n" +
" WHERE E.e_departamento =D.id_departamento AND e.establecimiento =es.id_establecimiento AND e.puesto =p.id_puesto AND e.estado =1 ";
        
        //seteo el modelo a la tabla
        jTbl_Datos.setModel(JM.LlenarJTable(consulta));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb1;
    private javax.swing.JComboBox<String> cmb2;
    private javax.swing.JComboBox<String> cmb3;
    private javax.swing.JButton jBtn_Agregar;
    private javax.swing.JButton jBtn_Consultar;
    private javax.swing.JButton jBtn_Eliminar;
    private javax.swing.JButton jBtn_Modificar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPnl_BarraTittle;
    private javax.swing.JPanel jPnl_Botones;
    private javax.swing.JPanel jPnl_Contenedor;
    private javax.swing.JPanel jPnl_ContenedorTabla;
    private javax.swing.JPanel jPnl_Controles;
    private javax.swing.JScrollPane jSp_ContenedorTabla;
    private javax.swing.JTable jTbl_Datos;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt11;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
