/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

/**
 *
 * @author Danie
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnl_Contenedor = new javax.swing.JPanel();
        jPnl_BarraTittle = new javax.swing.JPanel();
        jLb_Titulo = new javax.swing.JLabel();
        jPnl_ContenedorTabla = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPnl_Controles = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(940, 670));
        setMinimumSize(new java.awt.Dimension(940, 670));
        setPreferredSize(new java.awt.Dimension(940, 670));
        setSize(new java.awt.Dimension(940, 670));
        getContentPane().setLayout(null);

        jPnl_Contenedor.setBackground(new java.awt.Color(113, 127, 131));
        jPnl_Contenedor.setMaximumSize(new java.awt.Dimension(940, 670));
        jPnl_Contenedor.setLayout(null);

        jPnl_BarraTittle.setBackground(new java.awt.Color(44, 62, 80));

        jLb_Titulo.setBackground(new java.awt.Color(44, 62, 80));
        jLb_Titulo.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLb_Titulo.setForeground(new java.awt.Color(245, 245, 245));
        jLb_Titulo.setOpaque(true);
        jLb_Titulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLb_TituloMouseDragged(evt);
            }
        });
        jLb_Titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLb_TituloMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPnl_BarraTittleLayout = new javax.swing.GroupLayout(jPnl_BarraTittle);
        jPnl_BarraTittle.setLayout(jPnl_BarraTittleLayout);
        jPnl_BarraTittleLayout.setHorizontalGroup(
            jPnl_BarraTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_BarraTittleLayout.createSequentialGroup()
                .addComponent(jLb_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPnl_BarraTittleLayout.setVerticalGroup(
            jPnl_BarraTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLb_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPnl_Contenedor.add(jPnl_BarraTittle);
        jPnl_BarraTittle.setBounds(0, 0, 840, 30);

        jPnl_ContenedorTabla.setBackground(new java.awt.Color(44, 62, 80));
        jPnl_ContenedorTabla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPnl_ContenedorTabla.setOpaque(false);
        jPnl_ContenedorTabla.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tabla2.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        jPnl_ContenedorTabla.add(jLabel10);
        jLabel10.setBounds(30, 100, 130, 110);

        jLabel11.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Empleados");
        jPnl_ContenedorTabla.add(jLabel11);
        jLabel11.setBounds(40, 220, 100, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tabla2.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        jPnl_ContenedorTabla.add(jLabel12);
        jLabel12.setBounds(230, 100, 130, 110);

        jLabel13.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Incapacidad");
        jPnl_ContenedorTabla.add(jLabel13);
        jLabel13.setBounds(230, 220, 100, 30);

        jLabel14.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Puesto");
        jPnl_ContenedorTabla.add(jLabel14);
        jLabel14.setBounds(440, 220, 100, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tabla2.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        jPnl_ContenedorTabla.add(jLabel15);
        jLabel15.setBounds(430, 100, 130, 110);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tabla2.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel16MousePressed(evt);
            }
        });
        jPnl_ContenedorTabla.add(jLabel16);
        jLabel16.setBounds(630, 100, 130, 110);

        jLabel17.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Establecimiento");
        jPnl_ContenedorTabla.add(jLabel17);
        jLabel17.setBounds(650, 210, 100, 30);

        jPnl_Contenedor.add(jPnl_ContenedorTabla);
        jPnl_ContenedorTabla.setBounds(10, 239, 810, 300);

        jPnl_Controles.setBackground(new java.awt.Color(44, 62, 80));
        jPnl_Controles.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPnl_Controles.setOpaque(false);
        jPnl_Controles.setLayout(null);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPnl_Controles.add(jSeparator1);
        jSeparator1.setBounds(580, 0, 0, 198);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPnl_Controles.add(jSeparator2);
        jSeparator2.setBounds(580, 0, 0, 198);

        jLabel2.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Diagnostico");
        jPnl_Controles.add(jLabel2);
        jLabel2.setBounds(660, 120, 100, 30);

        jLabel3.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("GrupoOcup");
        jPnl_Controles.add(jLabel3);
        jLabel3.setBounds(40, 120, 100, 30);

        jLabel4.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Centro");
        jPnl_Controles.add(jLabel4);
        jLabel4.setBounds(240, 120, 100, 30);

        jLabel5.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Departamento");
        jPnl_Controles.add(jLabel5);
        jLabel5.setBounds(440, 120, 100, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tabla1.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPnl_Controles.add(jLabel6);
        jLabel6.setBounds(630, 10, 130, 110);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tabla1.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        jPnl_Controles.add(jLabel7);
        jLabel7.setBounds(30, 10, 130, 110);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tabla1.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPnl_Controles.add(jLabel8);
        jLabel8.setBounds(230, 10, 130, 110);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tabla1.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPnl_Controles.add(jLabel9);
        jLabel9.setBounds(430, 10, 130, 110);

        jPnl_Contenedor.add(jPnl_Controles);
        jPnl_Controles.setBounds(10, 74, 810, 160);

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Incapacidad");
        jPnl_Contenedor.add(jLabel1);
        jLabel1.setBounds(184, 34, 400, 40);

        getContentPane().add(jPnl_Contenedor);
        jPnl_Contenedor.setBounds(0, 0, 940, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLb_TituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLb_TituloMousePressed
        //obtiene las cordenadas X y Y del label en la pantalla
      
    }//GEN-LAST:event_jLb_TituloMousePressed

    private void jLb_TituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLb_TituloMouseDragged
        //reposiciona el formulario, hace que se pueda mover basicamente
       
    }//GEN-LAST:event_jLb_TituloMouseDragged

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        GrupoOcup frm = new GrupoOcup();
        frm.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
          Centro frm = new Centro();
        frm.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
          Departamento frm = new Departamento();
        frm.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
            Puesto frm = new Puesto();
        frm.setVisible(true);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
         Diagnostico frm = new Diagnostico();
        frm.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
         Empleados frm = new Empleados();
        frm.setVisible(true);
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        // TODO add your handling code here:
         Incapacidad frm = new Incapacidad();
        frm.setVisible(true);
    }//GEN-LAST:event_jLabel12MousePressed

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MousePressed

    private void jLabel16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MousePressed
        // TODO add your handling code here:
         Establecimiento frm = new Establecimiento();
        frm.setVisible(true);
    }//GEN-LAST:event_jLabel16MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLb_Titulo;
    private javax.swing.JPanel jPnl_BarraTittle;
    private javax.swing.JPanel jPnl_Contenedor;
    private javax.swing.JPanel jPnl_ContenedorTabla;
    private javax.swing.JPanel jPnl_Controles;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
